
import { Sparkles, Zap, Gem, Clock, Flame, Snowflake, Sun, Moon, Star, Zap as ChromeIcon, Waves } from 'lucide-react';
import type { ComboPreset } from './types';

export const COMBO_PRESETS: ComboPreset[] = [
  {
    id: 'holographic-burst',
    name: 'Holographic',
    icon: Sparkles,
    description: 'Rainbow holographic with chrome accents',
    materialHint: 'Deep blue holographic surface',
    effects: {
      holographic: 85,
      chrome: 45,
      foil: 0,
      vintage: 0,
      prismatic: 0,
      aurora: 0,
      crystal: 0,
      lunar: 0,
      waves: 0,
      interference: 0,
      gold: 0,
      ice: 0,
      prizm: 0,
      foilspray: 0,
      brushedmetal: 0
    }
  },
  {
    id: 'metallic-prizm',
    name: 'Prizm',
    icon: Gem,
    description: 'Subtle spectrum film with balanced color',
    materialHint: 'Delicate spectrum film over card surface',
    effects: {
      holographic: 0,
      chrome: 0,
      foil: 0,
      vintage: 0,
      prismatic: 0,
      aurora: 0,
      crystal: 0,
      lunar: 0,
      waves: 0,
      interference: 0,
      gold: 0,
      ice: 0,
      prizm: 40,
      foilspray: 0,
      brushedmetal: 25
    }
  },
  {
    id: 'crystal-interference',
    name: 'Crystal',
    icon: Zap,
    description: 'Crystal facets with soap bubble effects',
    materialHint: 'Translucent crystal surface with light dispersion',
    effects: {
      holographic: 0,
      chrome: 0,
      foil: 0,
      vintage: 0,
      prismatic: 0,
      aurora: 0,
      crystal: 80,
      lunar: 0,
      waves: 0,
      interference: 60,
      gold: 0,
      ice: 0,
      prizm: 0,
      foilspray: 0,
      brushedmetal: 0
    }
  },
  {
    id: 'vintage-foil',
    name: 'Vintage',
    icon: Clock,
    description: 'Aged patina with metallic foil spray',
    materialHint: 'Weathered surface with vintage texture',
    effects: {
      holographic: 0,
      chrome: 0,
      foil: 0,
      vintage: 65,
      prismatic: 0,
      aurora: 0,
      crystal: 0,
      lunar: 0,
      waves: 0,
      interference: 0,
      gold: 0,
      ice: 0,
      prizm: 0,
      foilspray: 50,
      brushedmetal: 0
    }
  },
  {
    id: 'golden-fire',
    name: 'Golden',
    icon: Flame,
    description: 'Warm gold tones with chromatic shift',
    materialHint: 'Rich golden surface with warm reflections',
    effects: {
      holographic: 0,
      chrome: 40,
      foil: 0,
      vintage: 0,
      prismatic: 0,
      aurora: 0,
      crystal: 0,
      lunar: 0,
      waves: 0,
      interference: 0,
      gold: 75,
      ice: 0,
      prizm: 0,
      foilspray: 0,
      brushedmetal: 0
    }
  },
  {
    id: 'ice-crystal',
    name: 'Ice',
    icon: Snowflake,
    description: 'Cool crystal with silver highlights',
    materialHint: 'Frosted crystal surface with silver accents',
    effects: {
      holographic: 0,
      chrome: 35,
      foil: 0,
      vintage: 0,
      prismatic: 0,
      aurora: 0,
      crystal: 70,
      lunar: 0,
      waves: 0,
      interference: 0,
      gold: 0,
      ice: 0,
      prizm: 0,
      foilspray: 0,
      brushedmetal: 0
    }
  },
  {
    id: 'aurora-flare',
    name: 'Aurora',
    icon: Sun,
    description: 'Aurora-like effect with dynamic wave movement',
    materialHint: 'Shimmering aurora with flowing blue-green waves',
    effects: {
      holographic: 0,
      chrome: 0,
      foil: 0,
      vintage: 0,
      prismatic: 0,
      aurora: 70,
      crystal: 0,
      lunar: 0,
      waves: 35,
      interference: 25,
      gold: 0,
      ice: 0,
      prizm: 0,
      foilspray: 0,
      brushedmetal: 0
    }
  },
  {
    id: 'lunar-shimmer',
    name: 'Lunar',
    icon: Moon,
    description: 'Subtle interference with vintage charm',
    materialHint: 'Soft silvery surface with gentle interference patterns',
    effects: {
      holographic: 0,
      chrome: 0,
      foil: 0,
      vintage: 35,
      prismatic: 0,
      aurora: 0,
      crystal: 0,
      lunar: 0,
      waves: 0,
      interference: 45,
      gold: 0,
      ice: 0,
      prizm: 0,
      foilspray: 0,
      brushedmetal: 0
    }
  },
  {
    id: 'starlight-spray',
    name: 'Starlight',
    icon: Star,
    description: 'Sparkling foil spray with atmospheric layers',
    materialHint: 'Metallic chrome surface with starlight atmosphere',
    effects: {
      holographic: 0,
      chrome: 0,
      foil: 0,
      vintage: 0,
      prismatic: 0,
      aurora: 0,
      crystal: 0,
      lunar: 0,
      waves: 0,
      interference: 0,
      gold: 0,
      ice: 0,
      prizm: 35,
      foilspray: 65,
      brushedmetal: 0
    }
  },
  {
    id: 'chrome-burst',
    name: 'Chrome',
    icon: ChromeIcon,
    description: 'Pure chrome with brushed metal finish',
    materialHint: 'Polished chrome surface with directional brushing',
    effects: {
      holographic: 0,
      chrome: 80,
      foil: 0,
      vintage: 0,
      prismatic: 0,
      aurora: 0,
      crystal: 0,
      lunar: 0,
      waves: 0,
      interference: 0,
      gold: 0,
      ice: 0,
      prizm: 0,
      foilspray: 0,
      brushedmetal: 40
    }
  },
  {
    id: 'ocean-waves',
    name: 'Ocean',
    icon: Waves,
    description: 'Gentle ocean waves with subtle prismatic light refraction',
    materialHint: 'Calm ocean surface with natural wave movement',
    effects: {
      holographic: 0,
      chrome: 0,
      foil: 0,
      vintage: 0,
      prismatic: 0,
      aurora: 0,
      crystal: 0,
      lunar: 0,
      waves: 45,
      interference: 25,
      gold: 0,
      ice: 0,
      prizm: 15,
      foilspray: 0,
      brushedmetal: 0
    }
  }
];
