
import { Sparkles, Zap, Gem, Clock, Flame, Snowflake, Sun, Moon, Star, Waves, Chrome, Diamond, Palette } from 'lucide-react';
import type { ComboPreset } from './types';

export const ENHANCED_COMBO_PRESETS: ComboPreset[] = [
  {
    id: 'custom-style',
    name: 'Custom',
    icon: Palette,
    emoji: '🎨',
    category: 'Personal',
    description: 'Create your own unique style with simplified controls',
    materialHint: 'Customizable surface with your personal touch',
    tags: ['Personal', 'Creative', 'Custom'],
    effects: {
      holographic: 0,
      chrome: 0,
      foil: 0,
      vintage: 0,
      prismatic: 0,
      aurora: 0,
      crystal: 0,
      lunar: 0,
      waves: 0,
      interference: 0,
      gold: 0,
      ice: 0,
      prizm: 0,
      foilspray: 0,
      brushedmetal: 0
    }
  },
  {
    id: 'holographic-burst',
    name: 'Holographic',
    icon: Sparkles,
    emoji: '🌈',
    category: 'Premium',
    description: 'Classic holographic trading card with rainbow shimmer',
    materialHint: 'Deep holographic surface with rainbow color shifts',
    tags: ['Popular', 'Trading Cards', 'Premium'],
    effects: {
      holographic: 85,
      chrome: 45,
      foil: 0,
      vintage: 0,
      prismatic: 0,
      aurora: 0,
      crystal: 0,
      lunar: 0,
      waves: 0,
      interference: 0,
      gold: 0,
      ice: 0,
      prizm: 0,
      foilspray: 0,
      brushedmetal: 0
    }
  },
  {
    id: 'crystal-interference',
    name: 'Crystal',
    icon: Diamond,
    emoji: '💎',
    category: 'Specialty',
    description: 'Multi-faceted crystal with geometric light patterns',
    materialHint: 'Translucent crystal surface with brilliant light dispersion',
    tags: ['Luxury', 'Geometric', 'Brilliant'],
    effects: {
      holographic: 0,
      chrome: 0,
      foil: 0,
      vintage: 0,
      prismatic: 0,
      aurora: 0,
      crystal: 80,
      lunar: 0,
      waves: 0,
      interference: 60,
      gold: 0,
      ice: 0,
      prizm: 0,
      foilspray: 0,
      brushedmetal: 0
    }
  },
  {
    id: 'chrome-burst',
    name: 'Chrome',
    icon: Chrome,
    emoji: '🪞',
    category: 'Metallic',
    description: 'Ultra-reflective chrome finish with sharp highlights',
    materialHint: 'Polished chrome surface with mirror-like reflections',
    tags: ['Modern', 'Reflective', 'Sharp'],
    effects: {
      holographic: 0,
      chrome: 80,
      foil: 0,
      vintage: 0,
      prismatic: 0,
      aurora: 0,
      crystal: 0,
      lunar: 0,
      waves: 0,
      interference: 0,
      gold: 0,
      ice: 0,
      prizm: 0,
      foilspray: 0,
      brushedmetal: 40
    }
  },
  {
    id: 'golden-fire',
    name: 'Golden',
    icon: Flame,
    emoji: '🏆',
    category: 'Premium',
    description: 'Luxurious gold finish with warm reflections',
    materialHint: 'Rich golden surface with authentic shimmer',
    tags: ['Luxury', 'Warm', 'Premium'],
    effects: {
      holographic: 0,
      chrome: 40,
      foil: 0,
      vintage: 0,
      prismatic: 0,
      aurora: 0,
      crystal: 0,
      lunar: 0,
      waves: 0,
      interference: 0,
      gold: 75,
      ice: 0,
      prizm: 0,
      foilspray: 0,
      brushedmetal: 0
    }
  },
  {
    id: 'ocean-waves',
    name: 'Ocean',
    icon: Waves,
    emoji: '🌊',
    category: 'Atmospheric',
    description: 'Gentle ocean waves with natural movement',
    materialHint: 'Calm ocean surface with flowing wave patterns',
    tags: ['Natural', 'Flowing', 'Calm'],
    effects: {
      holographic: 0,
      chrome: 0,
      foil: 0,
      vintage: 0,
      prismatic: 0,
      aurora: 0,
      crystal: 0,
      lunar: 0,
      waves: 45,
      interference: 25,
      gold: 0,
      ice: 0,
      prizm: 15,
      foilspray: 0,
      brushedmetal: 0
    }
  },
  {
    id: 'aurora-flare',
    name: 'Aurora',
    icon: Sun,
    emoji: '🌌',
    category: 'Atmospheric',
    description: 'Aurora-like effect with dynamic color shifts',
    materialHint: 'Shimmering aurora with flowing light waves',
    tags: ['Dynamic', 'Colorful', 'Magical'],
    effects: {
      holographic: 0,
      chrome: 0,
      foil: 0,
      vintage: 0,
      prismatic: 0,
      aurora: 70,
      crystal: 0,
      lunar: 0,
      waves: 35,
      interference: 25,
      gold: 0,
      ice: 0,
      prizm: 0,
      foilspray: 0,
      brushedmetal: 0
    }
  },
  {
    id: 'metallic-prizm',
    name: 'Prizm',
    icon: Gem,
    emoji: '🔮',
    category: 'Specialty',
    description: 'Subtle spectrum film with balanced color separation',
    materialHint: 'Delicate spectrum film over metallic surface',
    tags: ['Balanced', 'Spectrum', 'Subtle'],
    effects: {
      holographic: 0,
      chrome: 0,
      foil: 0,
      vintage: 0,
      prismatic: 0,
      aurora: 0,
      crystal: 0,
      lunar: 0,
      waves: 0,
      interference: 0,
      gold: 0,
      ice: 0,
      prizm: 40,
      foilspray: 0,
      brushedmetal: 25
    }
  },
  {
    id: 'vintage-foil',
    name: 'Vintage',
    icon: Clock,
    emoji: '📜',
    category: 'Classic',
    description: 'Aged patina with classic metallic foil',
    materialHint: 'Weathered surface with vintage character',
    tags: ['Classic', 'Aged', 'Character'],
    effects: {
      holographic: 0,
      chrome: 0,
      foil: 0,
      vintage: 65,
      prismatic: 0,
      aurora: 0,
      crystal: 0,
      lunar: 0,
      waves: 0,
      interference: 0,
      gold: 0,
      ice: 0,
      prizm: 0,
      foilspray: 50,
      brushedmetal: 0
    }
  },
  {
    id: 'ice-crystal',
    name: 'Ice',
    icon: Snowflake,
    emoji: '❄️',
    category: 'Atmospheric',
    description: 'Cool crystal surface with silver highlights',
    materialHint: 'Frosted crystal with natural ice patterns',
    tags: ['Cool', 'Natural', 'Crisp'],
    effects: {
      holographic: 0,
      chrome: 35,
      foil: 0,
      vintage: 0,
      prismatic: 0,
      aurora: 0,
      crystal: 70,
      lunar: 0,
      waves: 0,
      interference: 0,
      gold: 0,
      ice: 0,
      prizm: 0,
      foilspray: 0,
      brushedmetal: 0
    }
  },
  {
    id: 'starlight-spray',
    name: 'Starlight',
    icon: Star,
    emoji: '✨',
    category: 'Atmospheric',
    description: 'Sparkling foil spray with atmospheric shimmer',
    materialHint: 'Metallic surface with starlight atmosphere',
    tags: ['Sparkling', 'Atmospheric', 'Shimmer'],
    effects: {
      holographic: 0,
      chrome: 0,
      foil: 0,
      vintage: 0,
      prismatic: 0,
      aurora: 0,
      crystal: 0,
      lunar: 0,
      waves: 0,
      interference: 0,
      gold: 0,
      ice: 0,
      prizm: 35,
      foilspray: 65,
      brushedmetal: 0
    }
  },
  {
    id: 'lunar-shimmer',
    name: 'Lunar',
    icon: Moon,
    emoji: '🌙',
    category: 'Classic',
    description: 'Subtle interference with vintage space charm',
    materialHint: 'Soft silvery surface with gentle patterns',
    tags: ['Subtle', 'Vintage', 'Space'],
    effects: {
      holographic: 0,
      chrome: 0,
      foil: 0,
      vintage: 35,
      prismatic: 0,
      aurora: 0,
      crystal: 0,
      lunar: 0,
      waves: 0,
      interference: 45,
      gold: 0,
      ice: 0,
      prizm: 0,
      foilspray: 0,
      brushedmetal: 0
    }
  }
];
