-- Phase 3: US Sports Teams Data Collection (Fixed)
-- Populate major US sports leagues with team data

-- NFL Teams (32 teams)
INSERT INTO sports_teams (id, name, city, team_abbreviation, league, sport, division, conference, primary_color, secondary_color, accent_color, logo_url, founded_year, is_active) VALUES
('nfl-arizona-cardinals', 'Cardinals', 'Arizona', 'ARI', 'NFL', 'American Football', 'NFC West', 'NFC', '#97233F', '#000000', '#FFB612', '/logos/nfl/cardinals.png', 1898, true),
('nfl-atlanta-falcons', 'Falcons', 'Atlanta', 'ATL', 'NFL', 'American Football', 'NFC South', 'NFC', '#A71930', '#000000', '#A5ACAF', '/logos/nfl/falcons.png', 1966, true),
('nfl-baltimore-ravens', 'Ravens', 'Baltimore', 'BAL', 'NFL', 'American Football', 'AFC North', 'AFC', '#241773', '#000000', '#9E7C0C', '/logos/nfl/ravens.png', 1996, true),
('nfl-buffalo-bills', 'Bills', 'Buffalo', 'BUF', 'NFL', 'American Football', 'AFC East', 'AFC', '#00338D', '#C60C30', '#FFFFFF', '/logos/nfl/bills.png', 1960, true),
('nfl-carolina-panthers', 'Panthers', 'Carolina', 'CAR', 'NFL', 'American Football', 'NFC South', 'NFC', '#0085CA', '#101820', '#BFC0BF', '/logos/nfl/panthers.png', 1995, true),
('nfl-chicago-bears', 'Bears', 'Chicago', 'CHI', 'NFL', 'American Football', 'NFC North', 'NFC', '#0B162A', '#C83803', '#FFFFFF', '/logos/nfl/bears.png', 1920, true),
('nfl-cincinnati-bengals', 'Bengals', 'Cincinnati', 'CIN', 'NFL', 'American Football', 'AFC North', 'AFC', '#FB4F14', '#000000', '#FFFFFF', '/logos/nfl/bengals.png', 1968, true),
('nfl-cleveland-browns', 'Browns', 'Cleveland', 'CLE', 'NFL', 'American Football', 'AFC North', 'AFC', '#311D00', '#FF3C00', '#FFFFFF', '/logos/nfl/browns.png', 1946, true),
('nfl-dallas-cowboys', 'Cowboys', 'Dallas', 'DAL', 'NFL', 'American Football', 'NFC East', 'NFC', '#003594', '#041E42', '#869397', '/logos/nfl/cowboys.png', 1960, true),
('nfl-denver-broncos', 'Broncos', 'Denver', 'DEN', 'NFL', 'American Football', 'AFC West', 'AFC', '#FB4F14', '#002244', '#FFFFFF', '/logos/nfl/broncos.png', 1960, true),
('nfl-detroit-lions', 'Lions', 'Detroit', 'DET', 'NFL', 'American Football', 'NFC North', 'NFC', '#0076B6', '#B0B7BC', '#000000', '/logos/nfl/lions.png', 1930, true),
('nfl-green-bay-packers', 'Packers', 'Green Bay', 'GB', 'NFL', 'American Football', 'NFC North', 'NFC', '#203731', '#FFB612', '#FFFFFF', '/logos/nfl/packers.png', 1919, true),
('nfl-houston-texans', 'Texans', 'Houston', 'HOU', 'NFL', 'American Football', 'AFC South', 'AFC', '#03202F', '#A71930', '#FFFFFF', '/logos/nfl/texans.png', 2002, true),
('nfl-indianapolis-colts', 'Colts', 'Indianapolis', 'IND', 'NFL', 'American Football', 'AFC South', 'AFC', '#002C5F', '#A2AAAD', '#FFFFFF', '/logos/nfl/colts.png', 1953, true),
('nfl-jacksonville-jaguars', 'Jaguars', 'Jacksonville', 'JAX', 'NFL', 'American Football', 'AFC South', 'AFC', '#006778', '#9F792C', '#000000', '/logos/nfl/jaguars.png', 1995, true),
('nfl-kansas-city-chiefs', 'Chiefs', 'Kansas City', 'KC', 'NFL', 'American Football', 'AFC West', 'AFC', '#E31837', '#FFB81C', '#FFFFFF', '/logos/nfl/chiefs.png', 1960, true),
('nfl-las-vegas-raiders', 'Raiders', 'Las Vegas', 'LV', 'NFL', 'American Football', 'AFC West', 'AFC', '#000000', '#A5ACAF', '#FFFFFF', '/logos/nfl/raiders.png', 1960, true),
('nfl-los-angeles-chargers', 'Chargers', 'Los Angeles', 'LAC', 'NFL', 'American Football', 'AFC West', 'AFC', '#0080C6', '#FFC20E', '#FFFFFF', '/logos/nfl/chargers.png', 1960, true),
('nfl-los-angeles-rams', 'Rams', 'Los Angeles', 'LAR', 'NFL', 'American Football', 'NFC West', 'NFC', '#003594', '#FFA300', '#FF8200', '/logos/nfl/rams.png', 1936, true),
('nfl-miami-dolphins', 'Dolphins', 'Miami', 'MIA', 'NFL', 'American Football', 'AFC East', 'AFC', '#008E97', '#FC4C02', '#005778', '/logos/nfl/dolphins.png', 1966, true),
('nfl-minnesota-vikings', 'Vikings', 'Minnesota', 'MIN', 'NFL', 'American Football', 'NFC North', 'NFC', '#4F2683', '#FFC62F', '#FFFFFF', '/logos/nfl/vikings.png', 1961, true),
('nfl-new-england-patriots', 'Patriots', 'New England', 'NE', 'NFL', 'American Football', 'AFC East', 'AFC', '#002244', '#C60C30', '#B0B7BC', '/logos/nfl/patriots.png', 1960, true),
('nfl-new-orleans-saints', 'Saints', 'New Orleans', 'NO', 'NFL', 'American Football', 'NFC South', 'NFC', '#D3BC8D', '#101820', '#FFFFFF', '/logos/nfl/saints.png', 1967, true),
('nfl-new-york-giants', 'Giants', 'New York', 'NYG', 'NFL', 'American Football', 'NFC East', 'NFC', '#0F2C92', '#A71930', '#A5ACAF', '/logos/nfl/giants.png', 1925, true),
('nfl-new-york-jets', 'Jets', 'New York', 'NYJ', 'NFL', 'American Football', 'AFC East', 'AFC', '#125740', '#000000', '#FFFFFF', '/logos/nfl/jets.png', 1960, true),
('nfl-philadelphia-eagles', 'Eagles', 'Philadelphia', 'PHI', 'NFL', 'American Football', 'NFC East', 'NFC', '#004C54', '#A5ACAF', '#ACC0C6', '/logos/nfl/eagles.png', 1933, true),
('nfl-pittsburgh-steelers', 'Steelers', 'Pittsburgh', 'PIT', 'NFL', 'American Football', 'AFC North', 'AFC', '#FFB612', '#101820', '#FFFFFF', '/logos/nfl/steelers.png', 1933, true),
('nfl-san-francisco-49ers', '49ers', 'San Francisco', 'SF', 'NFL', 'American Football', 'NFC West', 'NFC', '#AA0000', '#B3995D', '#FFFFFF', '/logos/nfl/49ers.png', 1946, true),
('nfl-seattle-seahawks', 'Seahawks', 'Seattle', 'SEA', 'NFL', 'American Football', 'NFC West', 'NFC', '#002244', '#69BE28', '#A5ACAF', '/logos/nfl/seahawks.png', 1976, true),
('nfl-tampa-bay-buccaneers', 'Buccaneers', 'Tampa Bay', 'TB', 'NFL', 'American Football', 'NFC South', 'NFC', '#D50A0A', '#FF7900', '#0A0A08', '/logos/nfl/buccaneers.png', 1976, true),
('nfl-tennessee-titans', 'Titans', 'Tennessee', 'TEN', 'NFL', 'American Football', 'AFC South', 'AFC', '#0C2340', '#4B92DB', '#C8102E', '/logos/nfl/titans.png', 1960, true),
('nfl-washington-commanders', 'Commanders', 'Washington', 'WAS', 'NFL', 'American Football', 'NFC East', 'NFC', '#5A1414', '#FFB612', '#FFFFFF', '/logos/nfl/commanders.png', 1932, true);

-- NBA Teams (30 teams)  
INSERT INTO sports_teams (id, name, city, team_abbreviation, league, sport, division, conference, primary_color, secondary_color, accent_color, logo_url, founded_year, is_active) VALUES
('nba-atlanta-hawks', 'Hawks', 'Atlanta', 'ATL', 'NBA', 'Basketball', 'Southeast', 'Eastern', '#E03A3E', '#C1D32F', '#26282A', '/logos/nba/hawks.png', 1946, true),
('nba-boston-celtics', 'Celtics', 'Boston', 'BOS', 'NBA', 'Basketball', 'Atlantic', 'Eastern', '#007A33', '#BA9653', '#963821', '/logos/nba/celtics.png', 1946, true),
('nba-brooklyn-nets', 'Nets', 'Brooklyn', 'BKN', 'NBA', 'Basketball', 'Atlantic', 'Eastern', '#000000', '#FFFFFF', '#777D84', '/logos/nba/nets.png', 1967, true),
('nba-charlotte-hornets', 'Hornets', 'Charlotte', 'CHA', 'NBA', 'Basketball', 'Southeast', 'Eastern', '#1D1160', '#00788C', '#A1A1A4', '/logos/nba/hornets.png', 1988, true),
('nba-chicago-bulls', 'Bulls', 'Chicago', 'CHI', 'NBA', 'Basketball', 'Central', 'Eastern', '#CE1141', '#000000', '#FFFFFF', '/logos/nba/bulls.png', 1966, true),
('nba-cleveland-cavaliers', 'Cavaliers', 'Cleveland', 'CLE', 'NBA', 'Basketball', 'Central', 'Eastern', '#860038', '#FDBB30', '#041E42', '/logos/nba/cavaliers.png', 1970, true),
('nba-dallas-mavericks', 'Mavericks', 'Dallas', 'DAL', 'NBA', 'Basketball', 'Southwest', 'Western', '#00538C', '#002B5E', '#B8C4CA', '/logos/nba/mavericks.png', 1980, true),
('nba-denver-nuggets', 'Nuggets', 'Denver', 'DEN', 'NBA', 'Basketball', 'Northwest', 'Western', '#0E2240', '#FEC524', '#8B2131', '/logos/nba/nuggets.png', 1967, true),
('nba-detroit-pistons', 'Pistons', 'Detroit', 'DET', 'NBA', 'Basketball', 'Central', 'Eastern', '#C8102E', '#1D42BA', '#BEC0C2', '/logos/nba/pistons.png', 1941, true),
('nba-golden-state-warriors', 'Warriors', 'Golden State', 'GSW', 'NBA', 'Basketball', 'Pacific', 'Western', '#1D428A', '#FFC72C', '#26282A', '/logos/nba/warriors.png', 1946, true),
('nba-houston-rockets', 'Rockets', 'Houston', 'HOU', 'NBA', 'Basketball', 'Southwest', 'Western', '#CE1141', '#000000', '#C4CED4', '/logos/nba/rockets.png', 1967, true),
('nba-indiana-pacers', 'Pacers', 'Indiana', 'IND', 'NBA', 'Basketball', 'Central', 'Eastern', '#002D62', '#FDBB30', '#BEC0C2', '/logos/nba/pacers.png', 1967, true),
('nba-los-angeles-clippers', 'Clippers', 'Los Angeles', 'LAC', 'NBA', 'Basketball', 'Pacific', 'Western', '#C8102E', '#1D428A', '#BEC0C2', '/logos/nba/clippers.png', 1970, true),
('nba-los-angeles-lakers', 'Lakers', 'Los Angeles', 'LAL', 'NBA', 'Basketball', 'Pacific', 'Western', '#552583', '#FDB927', '#000000', '/logos/nba/lakers.png', 1947, true),
('nba-memphis-grizzlies', 'Grizzlies', 'Memphis', 'MEM', 'NBA', 'Basketball', 'Southwest', 'Western', '#5D76A9', '#12173F', '#F5B112', '/logos/nba/grizzlies.png', 1995, true),
('nba-miami-heat', 'Heat', 'Miami', 'MIA', 'NBA', 'Basketball', 'Southeast', 'Eastern', '#98002E', '#F9A01B', '#000000', '/logos/nba/heat.png', 1988, true),
('nba-milwaukee-bucks', 'Bucks', 'Milwaukee', 'MIL', 'NBA', 'Basketball', 'Central', 'Eastern', '#00471B', '#EEE1C6', '#0077C0', '/logos/nba/bucks.png', 1968, true),
('nba-minnesota-timberwolves', 'Timberwolves', 'Minnesota', 'MIN', 'NBA', 'Basketball', 'Northwest', 'Western', '#0C2340', '#236192', '#9EA2A2', '/logos/nba/timberwolves.png', 1989, true),
('nba-new-orleans-pelicans', 'Pelicans', 'New Orleans', 'NOP', 'NBA', 'Basketball', 'Southwest', 'Western', '#0C2340', '#C8102E', '#85714D', '/logos/nba/pelicans.png', 1988, true),
('nba-new-york-knicks', 'Knicks', 'New York', 'NYK', 'NBA', 'Basketball', 'Atlantic', 'Eastern', '#006BB6', '#F58426', '#BEC0C2', '/logos/nba/knicks.png', 1946, true),
('nba-oklahoma-city-thunder', 'Thunder', 'Oklahoma City', 'OKC', 'NBA', 'Basketball', 'Northwest', 'Western', '#007AC1', '#EF3B24', '#002D62', '/logos/nba/thunder.png', 1967, true),
('nba-orlando-magic', 'Magic', 'Orlando', 'ORL', 'NBA', 'Basketball', 'Southeast', 'Eastern', '#0077C0', '#C4CED4', '#000000', '/logos/nba/magic.png', 1989, true),
('nba-philadelphia-76ers', '76ers', 'Philadelphia', 'PHI', 'NBA', 'Basketball', 'Atlantic', 'Eastern', '#006BB6', '#ED174C', '#002B5C', '/logos/nba/76ers.png', 1949, true),
('nba-phoenix-suns', 'Suns', 'Phoenix', 'PHX', 'NBA', 'Basketball', 'Pacific', 'Western', '#1D1160', '#E56020', '#F9AD1B', '/logos/nba/suns.png', 1968, true),
('nba-portland-trail-blazers', 'Trail Blazers', 'Portland', 'POR', 'NBA', 'Basketball', 'Northwest', 'Western', '#E03A3E', '#000000', '#FFFFFF', '/logos/nba/blazers.png', 1970, true),
('nba-sacramento-kings', 'Kings', 'Sacramento', 'SAC', 'NBA', 'Basketball', 'Pacific', 'Western', '#5A2D81', '#63727A', '#000000', '/logos/nba/kings.png', 1945, true),
('nba-san-antonio-spurs', 'Spurs', 'San Antonio', 'SA', 'NBA', 'Basketball', 'Southwest', 'Western', '#C4CED4', '#000000', '#000000', '/logos/nba/spurs.png', 1967, true),
('nba-toronto-raptors', 'Raptors', 'Toronto', 'TOR', 'NBA', 'Basketball', 'Atlantic', 'Eastern', '#CE1141', '#000000', '#A1A1A4', '/logos/nba/raptors.png', 1995, true),
('nba-utah-jazz', 'Jazz', 'Utah', 'UTA', 'NBA', 'Basketball', 'Northwest', 'Western', '#002B5C', '#00471B', '#F9A01B', '/logos/nba/jazz.png', 1974, true),
('nba-washington-wizards', 'Wizards', 'Washington', 'WAS', 'NBA', 'Basketball', 'Southeast', 'Eastern', '#002B5C', '#E31837', '#C4CED4', '/logos/nba/wizards.png', 1961, true);